### ISSUE TITLE
Software TX crash

### ISSUE THREAD

**Issue by muebau** [openplotter/openplotter-maiana#1]
Hello the tool worked fine for the first few moments. I have the NMEA2000 version.

After I touched the software tx switch things got very wrong. The device seem to be reset to "all zero". There is no MMSI, no name etc. anymore. Nothing seems to help anymore.

Tried:
- rewrite the values (with the tool)
- Power cycle
- reboot the system
- rewrite the values (with the tool)

I will try to write the values with a terminal again.

I tried to reach the device with the "cli" command and nothing happens.
The device starts with 
```
$PAISYS,,*01
$PAISTN,0,,,0,0,0,0,0*11
```
and seems to ignore any input (CR LF is on).

**Comment by sailoog** [comment]
following this issue here: https://github.com/peterantypas/maiana/discussions/81

**Comment by sailoog** [comment]
Can I close this issue?

**Comment by muebau** [comment]
I tested the device and it looks like there is something with the mainboard. I think a further investigation could be interesting. Peter and I are still in contact about this.

**Comment by sailoog** [comment]
OK, since this is not a software issue I will close this issue. Re-open if needed.
